// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi hugohook

    Schemes:
      http
    Host: user.implemented.local
    BasePath: /
    Version: 1.0.0
    License: MIT

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
